name: CI
on:
  pull_request:
    branches:
        - main

jobs:
  setup-test-lint:
    name: Setup, Test, and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm test
    - run: npm run lint:check
